name = "radar-dos-editais"
main = "src/index.ts"
compatibility_date = "2026-09-09"
account_id = "749b2e9b3642e4b03321d5830e81c195"
workers_dev = true

[observability]
enabled = true

# 06:00 America/Recife (UTC-3) — segunda a sábado
[triggers]
crons = ["0 9 * * 1-6"]

[[kv_namespaces]]
binding = "RADAR"
id = "8417ad17e4d847e0937c64bcb03edea5"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
